# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        c = {}
        for i in s:
            c[i] = c.get(i,0)+1 
            # c.get(i,0) is Used for finding the occurence of character in string in Dictionary.
        for i in t:
            if c.get(i,0) == 0:
                return i
            c[i] -= 1 # We found this character in t, so use up one occurrence of it.
      
